<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="bottom-Footer">
	<div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<small class="copyright">
			    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
			</small>
		</div>
		<!-- <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<div class="footer_right">
				<img src="<?php // echo $this->getViewFileUrl('Magento_Theme::images/payment-card.jpg'); ?>">
			</div>
		</div> -->
	</div>
</div>